export const PREFIX = 'RESET_PASSWORD'
export default {
    SET_RECAPTCHA_KEY: 'SET_RECAPTCHA_KEY',
    SET_RECAPTCHA_INSTANCE: 'SET_RECAPTCHA_INSTANCE',
    RESET_PASSWORD_VERIFY: 'RESET_PASSWORD_VERIFY',
    RESET_PASSWORD: 'RESET_PASSWORD'
}
