export const Prefix = 'HOUSE'
export default {
    GET_HOUSE_SESSION_ID: 'GET_HOUSE_SESSION_ID',
    GET_HOUSE_SESSION_DATA: 'GET_HOUSE_SESSION_DATA',
    GET_HOUSE_AUTHORIZED_ADDRESSES: 'GET_HOUSE_AUTHORIZED_ADDRESSES',
    GET_HOUSE_ALLOWANCE: 'GET_HOUSE_ALLOWANCE',
    SET_HOUSE_PURCHASED_CREDITS: 'SET_HOUSE_PURCHASED_CREDITS',
    PURCHASE_HOUSE_CREDITS: 'PURCHASE_HOUSE_CREDITS',
    APPROVE_AND_PURCHASE_HOUSE_CREDITS: 'APPROVE_AND_PURCHASE_HOUSE_CREDITS'
}
