export const BettingProviderActions = {
    ADDRESS: 'GET_ADDRESS',
    ALLOWANCE: 'GET_ALLOWANCE',
    CURRENT_SESSION: 'GET_CURRENT_SESSION',
    CLAIM_BET: 'CLAIM_BET',
    DEPOSITED_TOKENS: 'GET_DEPOSITED_TOKENS',
    HOUSE_ADDRESS: 'GET_HOUSE_ADDRESS',
    GAMES: 'GET_GAMES',
    GAME_ITEM: 'GET_GAME_ITEM',
    GAMES_COUNT: 'GET_GAMES_COUNT',
    GAME_PERIOD_OUTCOME: 'GET_GAME_PERIOD_OUTCOME',
    GAME_ODDS: 'GET_GAME_ODDS',
    GAME_ODDS_COUNT: 'GET_GAME_ODDS_COUNT',
    GAME_BET_LIMIT: 'GET_GAME_BET_LIMIT',
    GAME_BET_LIMIT_FOR_PERIOD: 'GET_GAME_LIMIT_FOR_PERIOD',
    USER_BETS: 'GET_USER_BETS',
    SPORTSORACLE_ADDRESS: 'GET_SPORTSORACLE_ADDRESS',
    STATS: 'GET_SESSION_STATS',
    SET_BET: 'SET_BET',
    SET_TIME: 'SET_TIME',
    TIME: 'GET_TIME',
    TOKEN_BALANCE: 'GET_TOKEN_BALANCE',
}

export const OracleActions = {
    GET_GAMES: 'GET_GAMES',
    GET_GAME_ITEM: 'GET_GAME_ITEM',
    GET_GAMES_COUNT: 'GET_GAMES_COUNT',
    GET_GAME_UPDATE_COST: 'GET_GAME_UPDATE_COST',
    GET_REQUESTED_PROVIDER_ADDRESSES: 'GET_REQUESTED_PROVIDER_ADDRESSES',
    GET_ACCEPTED_PROVIDER_ADDRESSES: 'GET_ACCEPTED_PROVIDER_ADDRESSES',
    GET_OWNER: 'GET_OWNER',
    GET_TIME: 'GET_TIME',
    SET_TIME: 'SET_TIME'
}

export const BalanceActions = {
    GET_TOKENS: 'GET_TOKENS',
    DEPOSIT_TOKENS: 'DEPOSIT_TOKENS',
    WITHDRAW_TOKENS: 'WITHDRAW_TOKENS',
    APPROVE_AND_DEPOSIT_TOKENS: 'APPROVE_AND_DEPOSIT_TOKENS'
}
