export const Prefix = 'BETTING_PROVIDER'
export default {
    CLAIM_BET: 'CLAIM_BET',

    GET_ADDRESS: 'GET_ADDRESS',
    GET_ALLOWANCE: 'GET_ALLOWANCE',
    GET_CURRENT_SESSION: 'GET_CURRENT_SESSION',
    GET_DEPOSITED_TOKENS: 'GET_DEPOSITED_TOKENS',
    GET_HOUSE_ADDRESS: 'GET_HOUSE_ADDRESS',
    GET_GAMES: 'GET_GAMES',
    GET_GAME_ITEM: 'GET_GAME_ITEM',
    GET_GAMES_COUNT: 'GET_GAMES_COUNT',
    GET_GAME_PERIOD_OUTCOME: 'GET_GAME_PERIOD_OUTCOME',
    GET_GAME_ODDS: 'GET_GAME_ODDS',
    GET_GAME_ODDS_COUNT: 'GET_GAME_ODDS_COUNT',
    GET_GAME_BET_LIMIT: 'GET_GAME_BET_LIMIT',
    GET_GAME_BET_LIMIT_FOR_PERIOD: 'GET_GAME_LIMIT_FOR_PERIOD',
    GET_USER_BETS: 'GET_USER_BETS',
    GET_SPORTSORACLE_ADDRESS: 'GET_SPORTSORACLE_ADDRESS',
    GET_STATS: 'GET_SESSION_STATS',
    GET_TIME: 'GET_TIME',
    GET_TOKEN_BALANCE: 'GET_TOKEN_BALANCE',

    SET_BET: 'SET_BET',
    SET_TIME: 'SET_TIME'
}
