export const PREFIX = 'SPINS'
export default {
    GET_AES_KEY: 'GET_AES_KEY',
    GET_CHANNEL_DETAILS: 'GET_CHANNEL_DETAILS',
    GET_LAST_SPIN: 'GET_LAST_SPIN',

    NONCE_INCREASE: 'NONCE_INCREASE',

    POST_SPIN: 'POST_SPIN'
}
