export const Prefix = 'BALANCE'
export default {
    GET_PUBLIC_ADDRESS: 'GET_PUBLIC_ADDRESS',
    GET_TOKENS: 'GET_TOKENS',
    GET_ETHER_BALANCE: 'GET_ETHER_BALANCE',
    DEPOSIT_TOKENS: 'DEPOSIT_TOKENS',
    WITHDRAW_TOKENS: 'WITHDRAW_TOKENS',
    APPROVE_AND_DEPOSIT_TOKENS: 'APPROVE_AND_DEPOSIT_TOKENS',
    FAUCET: 'FAUCET',
    LOGOUT: 'LOGOUT'
}
