apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: platform-frontend
  name: platform-frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: platform-frontend
    spec:
      containers:
      - image: us.gcr.io/dbet-platform/platform-frontend:1.0.12-beta
        name: platform-frontend
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        # livenessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 3010
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
