export const PREFIX = 'CASINO'
export default {
    GET_AES_KEY: 'GET_AES_KEY',
    GET_ALLOWANCE: 'GET_ALLOWANCE',
    GET_BALANCE: 'GET_BALANCE',
    GET_CHANNEL: 'GET_CHANNEL',
    GET_CHANNELS: 'GET_CHANNELS',
    GET_CHANNEL_DETAILS: 'GET_CHANNEL_DETAILS',
    GET_LAST_SPIN: 'GET_LAST_SPIN',
    GET_CHANNEL_DEPOSITS: 'GET_CHANNEL_DEPOSITS',
    SET_CHANNEL_DEPOSITED: 'SET_CHANNEL_DEPOSITED',
    SET_CHANNEL_ACTIVATED: 'SET_CHANNEL_ACTIVATED',
    SET_CHANNEL_CLAIMED: 'SET_CHANNEL_CLAIMED',
    SET_CHANNEL_FINALIZED: 'SET_CHANNEL_FINALIZED',
    WAIT_FOR_CHANNEL_ACTIVATION: 'WAIT_FOR_CHANNEL_ACTIVATION',
    CREATE_CHANNEL: 'CREATE_CHANNEL',
    DEPOSIT_TO_CHANNEL: 'DEPOSIT_TO_CHANNEL',
    FINALIZE_CHANNEL: 'FINALIZE_CHANNEL',
    CLAIM_CHANNEL: 'CLAIM_CHANNEL',

    DEPOSIT_CHIPS: 'DEPOSIT_CHIPS',
    APPROVE: 'APPROVE',
    WITHDRAW_CHIPS: 'WITHDRAW_CHIPS',

    NONCE_INCREASE: 'NONCE_INCREASE',
    POST_SPIN: 'POST_SPIN',

    SET_CHANNEL: 'SET_CHANNEL',
    GET_CASINO_LOGIN_STATUS: 'GET_CASINO_LOGIN_STATUS',
    AUTH_WALLET: 'AUTH_WALLET',
    GET_TOKENS: 'GET_TOKENS',
    GET_ETHER_BALANCE: 'GET_ETHER_BALANCE',
    FAUCET: 'FAUCET',
    GET_CURRENT_STAGE: 'GET_CURRENT_STAGE',
    SET_CURRENT_STAGE: 'SET_CURRENT_STAGE',
    DEPOSIT_TOKENS: 'DEPOSIT_TOKENS',
    WITHDRAW_TOKENS: 'WITHDRAW_TOKENS',
    APPROVE_AND_DEPOSIT_TOKENS: 'APPROVE_AND_DEPOSIT_TOKENS'
}
