export const PREFIX = 'APP'
export default {
    OPEN_ALERT: 'OPEN_ALERT',
    APP_LOADED: 'APP_LOADED',
    CLOSE_ALERT: 'CLOSE_ALERT',
    LOGOUT: 'LOGOUT',
    SET_USER_AUTHENTICATION_STATUS: 'SET_USER_AUTHENTICATION_STATUS'
}
