export const PREFIX = 'APP'
export default {
    OPEN_ALERT: 'OPEN_ALERT',
    APP_LOADED: 'APP_LOADED',
    CLOSE_ALERT: 'CLOSE_ALERT',
    LOGOUT: 'LOGOUT',
    CHECK_LOGIN: 'CHECK_LOGIN',
    GET_AUTHENTICATION_SUBJECT: 'GET_AUTHENTICATION_SUBJECT'
}
