export const PREFIX = 'APP'
export default {
    LOGOUT: 'LOGOUT',
    SET_USER_AUTHENTICATION_STATUS: 'SET_USER_AUTHENTICATION_STATUS',
    SET_HTTP_AUTH_BASE_URL: 'SET_HTTP_AUTH_BASE_URL',
    SET_ACCOUNT_IS_ACTIVATED: 'SET_ACCOUNT_IS_ACTIVATED'
}
