export const Prefix = 'ORACLE'
export default {
    GET_GAMES: 'GET_GAMES',
    GET_GAME_ITEM: 'GET_GAME_ITEM',
    GET_GAMES_COUNT: 'GET_GAMES_COUNT',
    GET_GAME_UPDATE_COST: 'GET_GAME_UPDATE_COST',
    GET_REQUESTED_PROVIDER_ADDRESSES: 'GET_REQUESTED_PROVIDER_ADDRESSES',
    GET_ACCEPTED_PROVIDER_ADDRESSES: 'GET_ACCEPTED_PROVIDER_ADDRESSES',
    GET_OWNER: 'GET_OWNER',
    GET_TIME: 'GET_TIME',
    SET_TIME: 'SET_TIME'
}
