export const PREFIX = 'MAIN'
export default {
    SET_HTTP_AUTH_HEADER: 'SET_HTTP_AUTH_HEADER',
    GET_PUBLIC_ADDRESS: 'GET_PUBLIC_ADDRESS',
    GET_TOKENS: 'GET_TOKENS',
    GET_ETHER_BALANCE: 'GET_ETHER_BALANCE',
    FAUCET: 'FAUCET',
    GET_USER_ACCOUNT: 'GET_USER_ACCOUNT',
    SET_ACCOUNT_HAS_ADDRESS: 'SET_ACCOUNT_HAS_ADDRESS',
    SET_ACCOUNT_IS_VERIFIED: 'SET_ACCOUNT_IS_VERIFIED',
    GET_ACCOUNT_ACTIVATION_STATUS: 'GET_ACCOUNT_ACTIVATION_STATUS'
}
