export const PREFIX = 'MAIN'
export default {
    SET_HTTP_AUTH_HEADER: 'SET_HTTP_AUTH_HEADER',
    GET_PUBLIC_ADDRESS: 'GET_PUBLIC_ADDRESS',
    GET_TOKENS: 'GET_TOKENS',
    GET_ETHER_BALANCE: 'GET_ETHER_BALANCE',
    FAUCET: 'FAUCET',
    GET_USER_PROFILE: 'GET_USER_PROFILE'
}
