export const PREFIX = 'SLOT_MANAGER'
export default {
    GET_AES_KEY: 'GET_AES_KEY',
    GET_ALLOWANCE: 'GET_ALLOWANCE',
    GET_BALANCE: 'GET_BALANCE',
    GET_CHANNELS: 'GET_CHANNELS',
    GET_CHANNEL_DETAILS: 'GET_CHANNEL_DETAILS',
    GET_LAST_SPIN: 'GET_LAST_SPIN',
    GET_SESSION_ID: 'GET_SESSION_ID',

    SET_CHANNEL_DEPOSITED: 'SET_CHANNEL_DEPOSITED',
    SET_CHANNEL_ACTIVATED: 'SET_CHANNEL_ACTIVATED',
    SET_CHANNEL_CLAIMED: 'SET_CHANNEL_CLAIMED',
    SET_CHANNEL_FINALIZED: 'SET_CHANNEL_FINALIZED',

    CREATE_CHANNEL: 'CREATE_CHANNEL',
    DEPOSIT_TO_CHANNEL: 'DEPOSIT_TO_CHANNEL',
    FINALIZE_CHANNEL: 'FINALIZE_CHANNEL',
    CLAIM_CHANNEL: 'CLAIM_CHANNEL',
    CLAIM_AND_WITHDRAW_CHANNEL: 'CLAIM_AND_WITHDRAW_CHANNEL',

    DEPOSIT_CHIPS: 'DEPOSIT_TO_CONTRACT',
    APPROVE_AND_DEPOSIT_CHIPS: 'APPROVE_AND_DEPOSIT_CHIPS',
    WITHDRAW_CHIPS: 'WITHDRAW_CHIPS',

    NONCE_INCREASE: 'NONCE_INCREASE',
    POST_SPIN: 'POST_SPIN',

    SET_CHANNEL: 'SET_CHANNEL',
    BUILD_CHANNEL: 'BUILD_CHANNEL'
}
