export const PREFIX = 'AUTH'
export default {
    SET_RECAPTCHA_KEY: 'SET_RECAPTCHA_KEY',
    SET_RECAPTCHA_INSTANCE: 'SET_RECAPTCHA_INSTANCE',
    CLOSE_ALERT: 'CLOSE_ALERT',
    SET_SUCCESS_MESSAGE: 'SET_SUCCESS_MESSAGE',
    SET_DEFAULT_STATUS: 'SET_DEFAULT_STATUS',
    ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    LOGIN: 'LOGIN',
    RESET_PASSWORD: 'RESET_PASSWORD',
    SIGN_UP: 'SIGN_UP',
}
