export const PREFIX = 'AUTH'
export default {
    SIGN_UP: 'SIGN_UP',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    RESET_PASSWORD_VERIFY: 'RESET_PASSWORD_VERIFY',
    RESET_PASSWORD: 'RESET_PASSWORD',
    LOGIN: 'LOGIN'
}
