export const PREFIX = 'ACCOUNT'
export default {
    SAVE_ACCOUNT_INFO: 'SAVE_ACCOUNT_INFO',
    SAVE_ACCOUNT_ADDRESS: 'SAVE_ACCOUNT_ADDRESS',
    REQUEST_ACTIVATION_EMAIL: 'REQUEST_ACTIVATION_EMAIL'
}
